# Generated by Django 4.1.2 on 2022-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engapp', '0002_book_delete_samplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他'), ('AA', 'BB')], max_length=100),
        ),
    ]
